dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - aom=3.9.1
  - attr=2.5.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.4
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - contourpy=1.3.2
  - cpython=3.10.16
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.90
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dav1d=1.2.1
  - dbus=1.13.6
  - double-conversion=3.3.1
  - expat=2.7.0
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - h2=4.2.0
  - harfbuzz=11.0.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - jack=1.9.22
  - jinja2=3.1.6
  - joblib=1.4.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - level-zero=1.21.8
  - libabseil=20250127.1
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libass=0.17.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.4
  - libclang13=20.1.4
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm20=20.1.4
  - liblzma=5.8.1
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.4
  - libtiff=4.7.0
  - libudev1=257.4
  - libunwind=1.6.2
  - liburing=2.9
  - libusb=1.0.28
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.1
  - libxml2=2.13.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=9.2.0
  - mysql-libs=9.2.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=1.26.4
  - nvidia-ml-py=12.570.86
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.56.3
  - patsy=1.0.1
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pycparser=2.22
  - pynvml=12.0.0
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.0
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - sdl2=2.32.54
  - sdl3=3.2.10
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=78.1.0
  - six=1.17.0
  - snappy=1.2.1
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - sympy=1.13.3
  - tbb=2022.1.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tornado=6.4.2
  - typing_extensions=4.13.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wayland-protocols=1.42
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - causal-conv1d==1.5.0.post8
      - einops==0.8.1
      - fsspec==2025.3.2
      - huggingface-hub==0.30.2
      - hyperpyyaml==1.2.2
      - mamba-ssm==2.2.4
      - ninja==1.11.1.4
      - psutil==7.0.0
      - regex==2024.11.6
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - speechbrain==1.0.3
      - thop==0.1.1-2209072238
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.51.1
